from llama_index.core import SimpleDirectoryReader
from llama_index.core.node_parser import (
    SentenceSplitter,
    SemanticSplitterNodeParser,
)
from llama_index.embeddings.openai import OpenAIEmbedding 
# from llama_index.embeddings.huggingface import HuggingFaceEmbedding 
# embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-zh")
documents = SimpleDirectoryReader(input_files=["90-Data/BlackMythWukong/BlackMythWukong-Wiki.txt"]).load_data()

# Create the semantic splitter
splitter = SemanticSplitterNodeParser(
    buffer_size=3,  # buffer size
    breakpoint_percentile_threshold=90, # breakpoint percentile threshold
    embed_model=OpenAIEmbedding()     # embedding model to use
)
# Create a base sentence splitter (as a control)
base_splitter = SentenceSplitter(
    # chunk_size=512
)


'''
buffer_size:
default value is 1
This parameter controls how many sentences are grouped together when evaluating semantic
similarity. When set to 1, each sentence is considered individually. When set greater than
1, multiple sentences are grouped together for evaluation -- e.g. if set to 3, every 3
sentences are treated as a group when evaluating semantic similarity.

breakpoint_percentile_threshold:
default value is 95
This parameter controls when a split point is created between sentence groups. It
represents the percentile threshold of cosine dissimilarity; when the dissimilarity
between sentence groups exceeds this threshold, a new node is created.
The smaller the value, the more nodes are generated (because the split threshold is
reached more easily). The larger the value, the fewer nodes are generated (because a
greater dissimilarity is required to split).

These two parameters together affect how the text is split:
buffer_size determines the granularity at which semantic similarity is evaluated
breakpoint_percentile_threshold determines how strict the splitting is
For example:
If buffer_size=2 and breakpoint_percentile_threshold=90: every 2 sentences are grouped
together, and a split happens once the dissimilarity between groups exceeds 90%, which
produces relatively more nodes.
If buffer_size=3 and breakpoint_percentile_threshold=98: every 3 sentences are grouped
together, and a greater dissimilarity is required to split, which produces relatively
fewer nodes.
'''


# Chunk the document using the semantic splitter
semantic_nodes = splitter.get_nodes_from_documents(documents)
print("\n=== Semantic Chunking Results ===")
print(f"Number of chunks generated by the semantic splitter: {len(semantic_nodes)}")
for i, node in enumerate(semantic_nodes, 1):
    print(f"\n--- Semantic Chunk {i} ---")
    print(f"Content:\n{node.text}")
    print("-" * 50)

# Chunk the document using the base sentence splitter
base_nodes = base_splitter.get_nodes_from_documents(documents)
print("\n=== Base Sentence Chunking Results ===")
print(f"Number of chunks generated by the base sentence splitter: {len(base_nodes)}")
for i, node in enumerate(base_nodes, 1):
    print(f"\n--- Sentence Chunk {i} ---")
    print(f"Content:\n{node.text}")
    print("-" * 50)
